export const departmentOffenses: Record<string, string[]> = {
  police: [
    "Armed Robbery",
    "Assault",
    "Domestic Violence",
    "Kidnapping",
    "Theft",
    "Fraud",
    "Drug Trafficking",
    "Cybercrime",
  ],
  immigration: [
    "Illegal Entry",
    "Visa Overstay",
    "Human Trafficking",
    "Passport Forgery",
  ],
  fireservice: [
    "Fire Outbreak",
    "Blocked Fire Exit",
    "Gas Leak",
    "Electrical Hazard",
  ],
  roadsafety: [
    "Accident",
    "Reckless Driving",
    "Traffic Violation",
    "Road Obstruction",
  ],
  dss: [
    "Suspicious Activity",
    "Intelligence Threat",
    "Covert Surveillance",
    "National Security Breach",
  ],
  civildefence: [
    "Pipeline Vandalism",
    "Critical Asset Threat",
    "Illegal Mining",
    "Infrastructure Sabotage",
  ],
  vigilante: [
    "Neighborhood Disturbance",
    "Suspicious Movement",
    "Local Theft",
    "Community Dispute",
  ],
  efcc: [
    "Money Laundering",
    "Embezzlement",
    "Bribery",
    "Financial Fraud",
    "Corruption",
  ],
};
